# Generated by Django 4.0.3 on 2024-01-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tale',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('imglink', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'tale',
                'managed': False,
            },
        ),
    ]
