# Generated by Django 4.0.3 on 2024-01-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_tale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('type', models.CharField(max_length=5)),
                ('personality', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'child',
                'managed': False,
            },
        ),
    ]
