# Generated by Django 4.0.3 on 2024-02-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ttssetting',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('ttsspeed', models.CharField(max_length=10)),
                ('ttsvoice', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ttssetting',
                'managed': False,
            },
        ),
    ]
