# Generated by Django 4.0.3 on 2024-03-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_ttssetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('q', models.CharField(db_column='Q', max_length=500)),
                ('a', models.CharField(db_column='A', max_length=500)),
                ('direction', models.CharField(max_length=10)),
                ('likes', models.IntegerField()),
            ],
            options={
                'db_table': 'qna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.FloatField()),
            ],
            options={
                'db_table': 'rate',
                'managed': False,
            },
        ),
    ]
