# Generated by Django 4.0.3 on 2024-03-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentlikes',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('writedate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'commentlikes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'favorite',
                'managed': False,
            },
        ),
    ]
