# Generated by Django 4.0.3 on 2024-03-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_commentlikes_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentReads',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('readdate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'recent_reads',
                'managed': False,
            },
        ),
    ]
